Setup Linter files
braincee/math-magicians pull request #3
Opened 2022-05-23 11:01 UTC by braincee

- I created a new react app called maths magicians
- I setup linters to check for liner errors.

2022-05-23 11:07 UTC, arslanbisharat requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

- [x] You have a descriptive Pull Request. 
- [ ] You have installed all the linters properly.
- [x] Project has met technical Requirements. 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-23 11:07 UTC, arslanbisharat commented on .eslintrc.json
> +{
- [ ] Please make sure you have added a descriptive Readme file added to your project. You can use the templates given by Microverse.

2022-05-23 11:23 UTC, julie-ify approved these changes
Hi @braincee, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-23 11:27 UTC, merged

2022-11-12 10:43 UTC, braincee commented
Thanks very much @arslanbisharat @julie-ify