Add calculator features and styling
braincee/math-magicians pull request #4
Opened 2022-05-23 23:18 UTC by braincee

- I created a directory called components.
- Inside the components directory I created a new Calculator.js file.
- I created a new Calculator.css file to add styling to the project.

2022-05-24 10:03 UTC, GzimAsani requested changes
### Hi @braincee  
 
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job so far :clap: 
 
 ## Required Changes 
- [ ] _Check inline comments below :arrow_double_down: _


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 10:03 UTC, GzimAsani commented on src/App.js
>  function App() {
- [ ] App.js should also be class-based. Kindly change this

2022-05-24 11:19 UTC, elmar8287 approved these changes
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 11:24 UTC, merged

2022-11-12 10:45 UTC, braincee commented
Thanks very much, @elmar8287 @GzimAsani 

![thank-you-gif-6](https://user-images.githubusercontent.com/78104544/201470552-3041ee5e-e99c-40bd-9ea9-875aa78e096a.gif)